version: '3'

services:
  web:
    build: ./web
    environment:
      - DJANGO_SUPERUSER_PASSWORD=1234
    command: bash -c "
      docker run -p 6379:6379 -d redis:5
      python3 manage.py createsuperuser && 
      python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'mesDB'
      MYSQL_USER: 'denis'
      MYSQL_PASSWORD: 'denis210203'
      MYSQL_ROOT_PASSWORD: 'denis210203'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql